/**
 * @file colors.settings.h
 * @author Maximilian (https://github.com/Maximilian04)
 * @brief Colors
 * @date 2022-11-21
 *
 * @copyright Copyright (c) 2022
 *
 */

#ifndef COLORS_SETTINGS_H
#define COLORS_SETTINGS_H

#define COLORS_SETTINGS_ADDRPOINTER_TEXTCOLOR "cyan"
// #define COLORS_SETTINGS_ADDRPOINTER_TEXTCOLOR #00C0C0

#define COLORS_SETTINGS_LOGICPOINTER_TEXTCOLOR "RosyBrown"

#define COLORS_SETTINGS_BADDATA_TEXTCOLOR "indianRed"

#define COLORS_SETTINGS_EMERGANCYMSG_TEXTCOLOR "orangeRed"

#define COLORS_SETTINGS_GRAPHNODE_BACKCOLOR "MistyRose"
#define COLORS_SETTINGS_GRAPHNODE_EDGECOLOR "RosyBrown"

#define COLORS_SETTINGS_GRAHARROW_FORWARD "coral"
#define COLORS_SETTINGS_GRAHARROW_BACKWARD "indigo"

#define COLORS_SETTINGS_CRINGE_TEXTCOLOR "MintCream"
#define COLORS_SETTINGS_NOTE_TEXTCOLOR "BlueViolet"

#endif // COLORS_SETTINGS_H
